[package]
name = "cursor_hero_worker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { workspace = true }
cursor_hero_worker_types = { workspace = true }
crossbeam-channel = { workspace = true }
tokio = {workspace = true}
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_Com",
] }