[package]
name = "gamepad_hell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gilrs = { version = "0.10.4", features = ["xinput"], default_features = false}
