[package]
name = "cursor_hero_ui_automation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { workspace = true }
uiautomation = { workspace = true }
itertools = { workspace = true }
cursor_hero_ui_automation_types = { workspace = true }
cursor_hero_winutils = { workspace = true }
cursor_hero_metrics = { workspace = true }
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Security"
] }
image = { workspace = true }

[dev-dependencies]
cursor_hero_memory_types = { workspace = true }
cursor_hero_worker = { workspace = true }