[package]
name = "cursor-hero"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bevy = { version = "0.11.3", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.20.0"
image = "0.24.7"
minifb = "0.25.0"
mouse-rs = "0.4.2"
rayon = "1.8.0"
screenshots = "0.8.4"
widestring = "1.0.2"
windows = { version = "0.51.1", features = ["Win32_Foundation", "Win32_Graphics_Gdi"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
