[package]
name = "cursor_hero_winutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursor_hero_metrics = { workspace = true }
bevy = { workspace = true }
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_UI_Input_KeyboardAndMouse",
    # "Win32_System_Com",
    # "Win32_UI_Accessibility",
    # "Gaming_Input",
    # "Win32_Gaming",
    # "Win32_System_Threading",
] }
image = {workspace = true}
anyhow = {workspace = true}
uiautomation = {workspace = true}
fxhash = {workspace = true}
widestring = {workspace = true}
