[package]
name = "cursor_hero_winutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursor_hero_metrics = { workspace = true }
bevy = { workspace = true }
windows = { workspace = true, features = [
    "Win32_Devices_HumanInterfaceDevice",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_LibraryLoader",
    "Win32_System_Ole",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
    "Win32_System_Variant",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
    # "Win32_UI_Accessibility",
    # "Gaming_Input",
    # "Win32_Gaming",
    # "Win32_System_Threading",
] }
image = {workspace = true}
anyhow = {workspace = true}
uiautomation = {workspace = true}
fxhash = {workspace = true}
widestring = {workspace = true}
enigo = {workspace = true}
once_cell = {workspace = true}
itertools = {workspace = true}
winreg = { workspace = true }
crossbeam-channel = { workspace = true }
cursor_hero_bevy = { workspace = true }
winit = { workspace = true } # TODO: remove me

[dev-dependencies]
cursor_hero_memory_types = { workspace = true }
cursor_hero_worker = { workspace = true }
bevy-inspector-egui = { workspace = true }
