[package]
name = "cursor_hero_winutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursor_hero_metrics = { workspace = true }
bevy = { workspace = true }
windows = { version = "0.51.1", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_UI_Input_KeyboardAndMouse",
    # "Win32_System_Com",
    # "Win32_UI_Accessibility",
    # "Gaming_Input",
    # "Win32_Gaming",
    # "Win32_System_Threading",
] }
image = "0.24.7"
anyhow = "1.0.75"
uiautomation = "0.7.3"
fxhash = "0.2.1"
widestring = "1.0.2"
