[package]
name = "dependency-hell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"

# [patch.crates-io]
# bevy_gilrs = { path = "../../bevy/crates/bevy_gilrs" }
