[package]
name = "cursor_hero_tts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { workspace = true }
cursor_hero_tts_types = { workspace = true }
tokio = {workspace = true}
reqwest = {workspace = true}
urlencoding = {workspace = true}
crossbeam-channel = { workspace = true }
