[package]
name = "cursor_hero_window_position"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { workspace = true }
cursor_hero_bevy = { workspace = true }
cursor_hero_window_position_types = { workspace = true }
cursor_hero_toolbelt_types = { workspace = true }
cursor_hero_tools = { workspace = true }
raw-window-handle = {workspace = true }
