[package]
name = "cursor_hero_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursor_hero_toolbelt = { workspace = true }
cursor_hero_input = { workspace = true }
cursor_hero_screen = { workspace = true }
cursor_hero_pointer = { workspace = true }
cursor_hero_winutils = { workspace = true }
cursor_hero_camera = { workspace = true }
cursor_hero_character = { workspace = true }
cursor_hero_movement = { workspace = true }
cursor_hero_glam = { workspace = true }
cursor_hero_data = { workspace = true }
cursor_hero_click_drag_character_movement = { workspace = true }
cursor_hero_physics = { workspace = true }
bevy = { workspace = true }
bevy-inspector-egui = { workspace = true }
bevy_xpbd_2d = { workspace = true }
crossbeam-channel = {workspace = true }
itertools = {workspace = true }
raw-window-handle = {workspace = true }
leafwing-input-manager = { workspace = true }
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Com",
    "Win32_UI_Accessibility",
    "Win32_UI_Input_KeyboardAndMouse",
    "Gaming_Input",
    "Win32_Gaming",
    "Win32_System_Threading",
] }
enigo = { workspace = true }