[package]
name = "cursor_hero_toolbelt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursor_hero_character_types = { workspace = true }
cursor_hero_bevy = { workspace = true }
cursor_hero_pointer_types = { workspace = true }
cursor_hero_input = { workspace = true }
cursor_hero_math = { workspace = true }
cursor_hero_sprint_tool_types = { workspace = true }
cursor_hero_toolbelt_types = { workspace = true }
cursor_hero_window_position_types = { workspace = true }
cursor_hero_xelu_prompts = { workspace = true }
bevy = { workspace = true }
bevy-inspector-egui = { workspace = true }
bevy_xpbd_2d = { workspace = true }
leafwing-input-manager = { workspace = true }
itertools = { workspace = true }
cursor_hero_host_fs_types = { workspace = true }