[package]
name = "cursor_hero_ui_watcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { workspace = true }
cursor_hero_ui_watcher_types = { workspace = true }
crossbeam-channel = { workspace = true }
cursor_hero_ui_automation = { workspace = true }
cursor_hero_environment_types = { workspace = true }
cursor_hero_observation_types = { workspace = true }
cursor_hero_memory_types = { workspace = true }
cursor_hero_character_types = { workspace = true }