[package]
name = "cursor_hero_taskbar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { workspace = true }
image = { workspace = true}
cursor_hero_environment = { workspace = true }
cursor_hero_bevy = { workspace = true }
cursor_hero_pointer_types = { workspace = true }
cursor_hero_screen = { workspace = true }
cursor_hero_toolbelt_types = { workspace = true }
cursor_hero_tools = { workspace = true }
cursor_hero_winutils = { workspace = true }
bevy_xpbd_2d = { workspace = true }
