[package]
name = "cursor_hero_ui_hover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { workspace = true }
cursor_hero_ui_hover_types = { workspace = true }
cursor_hero_ui_inspector_types = { workspace = true }
cursor_hero_ui_automation = { workspace = true }
cursor_hero_camera = { workspace = true }
cursor_hero_worker = { workspace = true }
cursor_hero_winutils = { workspace = true }
cursor_hero_cursor_types = { workspace = true }
cursor_hero_bevy = { workspace = true }
bevy_xpbd_2d = { workspace = true }
bevy_egui = {workspace = true}
